# Configuration for Alacritty, the GPU enhanced terminal emulator.
#
# See: /usr/share/doc/alacritty/example/alacritty.yml
#

---
bell:
  # Values for `animation`:
  #   - Ease
  #   - EaseOut
  #   - EaseOutSine
  #   - EaseOutQuad
  #   - EaseOutCubic
  #   - EaseOutQuart
  #   - EaseOutQuint
  #   - EaseOutExpo
  #   - EaseOutCirc
  #   - Linear
  animation: EaseOutSine
  color: '#99aa00'
  command: None
  duration: 200

# Colors (Based on Kanagawa)
colors:
  cursor:
    cursor: CellForeground
    text: CellBackground

  footer_bar:
    background: '#c5c8c6'
    foreground: '#1d1f21'

  hints:
    end:
      background: '#1d1f21'
      foreground: '#e9ff5e'
    start:
      background: '#e9ff5e'
      foreground: '#1d1f21'

  indexed_colors: []

  line_indicator:
    background: None
    foreground: None

  primary:
    background: '#0d0c0c'
    bright_foreground: '#eaeaea'
    dim_foreground: '#828482'
    foreground: '#c5c9c5'

  search:
    focused_match:
      background: '#0d0c0c'
      foreground: '#c5c9c5'
    matches:
      background: '#0d0c0c'
      foreground: '#828482'

  selection:
    background: CellForeground
    text: CellBackground

  # Bright colors
  bright:
    black:   '#12120f'
    blue:    '#7fb4ca'
    cyan:    '#7aa89f'
    green:   '#98bb6c'
    magenta: '#b8b4d0'
    red:     '#e82424'
    white:   '#ede8cb'
    yellow:  '#f9d791'

  # Dim colors
  # If not set, dim calculated based on normal colors
  dim:
    black:   '#181616'
    blue:    '#4d699b'
    cyan:    '#597b75'
    green:   '#8a9a7b'
    magenta: '#624c83'
    red:     '#c4746e'
    white:   '#c5c9c5'
    yellow:  '#c4b28a'

  # Normal colors
  normal:
    black:   '#0d0c0c'
    blue:    '#7e9cd8'
    cyan:    '#6a9589'
    green:   '#76946a'
    magenta: '#957fb8'
    red:     '#c34043'
    white:   '#dcd7ba'
    yellow:  '#e6c384'

  transparent_background_colors: false

  vi_mode_cursor:
    cursor: CellForeground
    text: CellBackground

cursor:
  blink_interval: 750   # milliseconds
  blink_timeout: 0
  style:
    # Never: Prevent the cursor from ever blinking
    # Off: Disable blinking by default
    # On: Enable blinking by default
    # Always: Force the cursor to always blink
    blinking: Never
    # ▇ Block
    # _ Underline
    # | Beam
    shape: Block

  thickness: 0.15  # Cursor thickness relative to the cell width (0.0 to 1.0)
  unfocused_hollow: true
  vi_mode_style: None

draw_bold_text_with_bright_colors: true

env:
  TERM: alacritty

font:
  bold:
    family: Fira Code Nerd Font
    style: Bold
  bold_italic:
    family: Roboto Mono Nerd Font
    style: Bold Italic

  builtin_box_drawing: false
  glyph_offset:
    x: 0
    y: 0

  italic:
    family: Roboto Mono Nerd Font
    style: Italic
  normal:
    family: Fira Code Nerd Font
    style: Regular

  offset:
    x: 0
    y: 0

  # Point size
  size: 13.0

# Offer IPC using `alacritty msg` (unix only)
ipc_socket: true

# Live config reload (changes require restart)
live_config_reload: true

mouse:
  double_click: { threshold: 200 }
  hide_when_typing: false
  triple_click: { threshold: 300 }

scrolling:
  history: 5000
  multiplier: 2

selection:
  save_to_clipboard: true
  semantic_escape_chars: ",│`|:\"' ()[]{}<>\t"

window:
  class:
    general: Alacritty
    instance: Alacritty

  decorations: full
  decorations_theme_variant: None

  dimensions:
    columns: 0
    lines: 0

  dynamic_padding: false
  dynamic_title: true
  opacity: 0.7

  padding:
    x: 0
    y: 0

  position:
    x: 0
    y: 0

  resize_increments: false
  startup_mode: Windowed
  title: Alacritty

# Shell Default:
#   - (Linux/BSD/macOS) `$SHELL` or the user's login shell, if `$SHELL` is unset
#   - (Windows) powershell
## shell:
##  program: '/usr/bin/bash'
##  args:
##    - --login

# Directory the shell is started in. If this is unset, or `None`, the working
# directory of the parent process will be used.
working_directory: None

# Hints
#
# Terminal hints can be used to find text or hyperlink in the visible part of
# the terminal and pipe it to other applications.
hints:
  # Keys used for the hint labels.
  alphabet: "jfkdls;ahgurieowpq"
  enabled:
    - binding:
        key: U
        mods: Control|Shift
      command: xdg-open
      hyperlinks: true
      mouse:
        enabled: true
        mods: None
      post_processing: true
      regex: "(ipfs:|ipns:|magnet:|mailto:|gemini:|gopher:\
              |https:|http:|news:|file:|git:|ssh:|ftp:)\
              [^\u0000-\u001F\u007F-\u009F<>\"\\s{-}\\^⟨⟩`]+"

key_bindings:
  - { key: Paste,                               action: Paste          }
  - { key: Copy,                                action: Copy           }
  - { key: PageUp,   mods: Shift,   mode: ~Alt, action: ScrollPageUp   }
  - { key: PageDown, mods: Shift,   mode: ~Alt, action: ScrollPageDown }
  - { key: Home,     mods: Shift,   mode: ~Alt, action: ScrollToTop    }
  - { key: End,      mods: Shift,   mode: ~Alt, action: ScrollToBottom }
  - { key: L,        mods: Control,             action: ClearLogNotice }
  - { key: L,        mods: Control, mode: ~Vi|~Search, chars: "\x0c"   }

  # Vi Mode
  - { key: Space,  mods: Shift|Control, mode: ~Search,    action: ToggleViMode   }
  - { key: Space,  mods: Shift|Control, mode: Vi|~Search, action: ScrollToBottom }
  - { key: Escape,                      mode: Vi|~Search, action: ClearSelection }
  - { key: I,                           mode: Vi|~Search, action: ToggleViMode   }
  - { key: I,                           mode: Vi|~Search, action: ScrollToBottom }
  - { key: C,      mods: Control,       mode: Vi|~Search, action: ToggleViMode   }
  - { key: Y,      mods: Control,       mode: Vi|~Search, action: ScrollLineUp   }
  - { key: E,      mods: Control,       mode: Vi|~Search, action: ScrollLineDown }
  - { key: G,                           mode: Vi|~Search, action: ScrollToTop    }
  - { key: G,      mods: Shift,         mode: Vi|~Search, action: ScrollToBottom }
  - { key: B,      mods: Control,       mode: Vi|~Search, action: ScrollPageUp   }
  - { key: F,      mods: Control,       mode: Vi|~Search, action: ScrollPageDown }
  - { key: U,      mods: Control,       mode: Vi|~Search, action: ScrollHalfPageUp }
  - { key: D,      mods: Control,       mode: Vi|~Search, action: ScrollHalfPageDown }
  - { key: Y,                           mode: Vi|~Search, action: Copy                    }
  - { key: Y,                           mode: Vi|~Search, action: ClearSelection          }
  - { key: Copy,                        mode: Vi|~Search, action: ClearSelection          }
  - { key: V,                           mode: Vi|~Search, action: ToggleNormalSelection   }
  - { key: V,      mods: Shift,         mode: Vi|~Search, action: ToggleLineSelection     }
  - { key: V,      mods: Control,       mode: Vi|~Search, action: ToggleBlockSelection    }
  - { key: V,      mods: Alt,           mode: Vi|~Search, action: ToggleSemanticSelection }
  - { key: Return,                      mode: Vi|~Search, action: Open                    }
  - { key: Z,                           mode: Vi|~Search, action: CenterAroundViCursor    }
  - { key: K,                           mode: Vi|~Search, action: Up                      }
  - { key: J,                           mode: Vi|~Search, action: Down                    }
  - { key: H,                           mode: Vi|~Search, action: Left                    }
  - { key: L,                           mode: Vi|~Search, action: Right                   }
  - { key: Up,                          mode: Vi|~Search, action: Up                      }
  - { key: Down,                        mode: Vi|~Search, action: Down                    }
  - { key: Left,                        mode: Vi|~Search, action: Left                    }
  - { key: Right,                       mode: Vi|~Search, action: Right                   }
  - { key: Key0,                        mode: Vi|~Search, action: First                   }
  - { key: Key4,   mods: Shift,         mode: Vi|~Search, action: Last                    }
  - { key: Key6,   mods: Shift,         mode: Vi|~Search, action: FirstOccupied           }
  - { key: H,      mods: Shift,         mode: Vi|~Search, action: High                    }
  - { key: M,      mods: Shift,         mode: Vi|~Search, action: Middle                  }
  - { key: L,      mods: Shift,         mode: Vi|~Search, action: Low                     }
  - { key: B,                           mode: Vi|~Search, action: SemanticLeft            }
  - { key: W,                           mode: Vi|~Search, action: SemanticRight           }
  - { key: E,                           mode: Vi|~Search, action: SemanticRightEnd        }
  - { key: B,      mods: Shift,         mode: Vi|~Search, action: WordLeft                }
  - { key: W,      mods: Shift,         mode: Vi|~Search, action: WordRight               }
  - { key: E,      mods: Shift,         mode: Vi|~Search, action: WordRightEnd            }
  - { key: Key5,   mods: Shift,         mode: Vi|~Search, action: Bracket                 }
  - { key: Slash,                       mode: Vi|~Search, action: SearchForward           }
  - { key: Slash,  mods: Shift,         mode: Vi|~Search, action: SearchBackward          }
  - { key: N,                           mode: Vi|~Search, action: SearchNext              }
  - { key: N,      mods: Shift,         mode: Vi|~Search, action: SearchPrevious          }

  # Search Mode
  - { key: Return,                mode: Search|Vi,  action: SearchConfirm         }
  - { key: Escape,                mode: Search,     action: SearchCancel          }
  - { key: C,      mods: Control, mode: Search,     action: SearchCancel          }
  - { key: U,      mods: Control, mode: Search,     action: SearchClear           }
  - { key: W,      mods: Control, mode: Search,     action: SearchDeleteWord      }
  - { key: P,      mods: Control, mode: Search,     action: SearchHistoryPrevious }
  - { key: N,      mods: Control, mode: Search,     action: SearchHistoryNext     }
  - { key: Up,                    mode: Search,     action: SearchHistoryPrevious }
  - { key: Down,                  mode: Search,     action: SearchHistoryNext     }
  - { key: Return,                mode: Search|~Vi, action: SearchFocusNext       }
  - { key: Return, mods: Shift,   mode: Search|~Vi, action: SearchFocusPrevious   }

  # (Windows, Linux, and BSD only)
  - { key: V,              mods: Control|Shift, mode: ~Vi,        action: Paste            }
  - { key: C,              mods: Control|Shift,                   action: Copy             }
  - { key: F,              mods: Control|Shift, mode: ~Search,    action: SearchForward    }
  - { key: B,              mods: Control|Shift, mode: ~Search,    action: SearchBackward   }
  - { key: C,              mods: Control|Shift, mode: Vi|~Search, action: ClearSelection   }
  - { key: Insert,         mods: Shift,                           action: PasteSelection   }
  - { key: Key0,           mods: Control,                         action: ResetFontSize    }
  - { key: Equals,         mods: Control,                         action: IncreaseFontSize }
  - { key: Plus,           mods: Control,                         action: IncreaseFontSize }
  - { key: NumpadAdd,      mods: Control,                         action: IncreaseFontSize }
  - { key: Minus,          mods: Control,                         action: DecreaseFontSize }
  - { key: NumpadSubtract, mods: Control,                         action: DecreaseFontSize }
