#!/bin/sh
#  Installs my entire Linix desktop environment into my $HOME directory.
#
#  Systemd --user Services used
#    - kanshi - Wayland daemon that automatically configures outputs
#    - mako - Notification daemon for Wayland
#    - mpd - Music daemon for linux
#

export scriptName=dfInstall

XDG_CONFIG_HOME="${XDG_CONFIG_HOME:=$HOME/.config}"
DOTFILE_GIT_REPO="${DOTFILE_GIT_REPO:=$HOME/devel/dotfiles}"
umask 0022

### Source install infrastructure
switch=''
. ./installSource.sh

### Configuration

HOME_FILES='
   .bash_profile
   .bashrc
   .inputrc
'

BIN_SCRIPTS='
   buArch
   chkcolor
   codepoint
   digpath
   monitor
   myCalc
   pathtrim
   rt
   spin
   startw
   viewJarManifest
'

CONFIG_FILES='
   alacritty/alacritty_arch.yml
   alacritty/alacritty.yml
   fish/completions/alacritty.fish
   fish/config.fish
   fish/conf.d/00-ensure-or-redo-init-env.fish
   fish/conf.d/abbrs.fish
   fish/conf.d/colors.fish
   fish/functions/archJDK.fish
   fish/functions/ax.fish
   fish/functions/cu.fish
   fish/functions/digpath.fish
   fish/functions/disable_touch_pad.fish
   fish/functions/enable_touch_pad.fish
   fish/functions/ev.fish
   fish/functions/fdot.fish
   fish/functions/ff.fish
   fish/functions/fields.fish
   fish/functions/fishcolors.fish
   fish/functions/fishterm.fish
   fish/functions/fm.fish
   fish/functions/fish_greeting.fish
   fish/functions/fish_mode_prompt.fish
   fish/functions/fish_prompt.fish
   fish/functions/fish_title.fish
   fish/functions/la.fish
   fish/functions/ldir.fish
   fish/functions/ldot.fish
   fish/functions/lf.fish
   fish/functions/lh.fish
   fish/functions/ll.fish
   fish/functions/mc.fish
   fish/functions/nsort.fish
   fish/functions/pathtrim.fish
   fish/functions/rc.fish
   fish/functions/ud.fish
   fish/functions/Wget.fish
   fish/functions/WgetM.fish
   fish/functions/b2b.fish
   fish/functions/b2d.fish
   fish/functions/b2h.fish
   fish/functions/b2o.fish
   fish/functions/d2b.fish
   fish/functions/d2d.fish
   fish/functions/d2h.fish
   fish/functions/d2o.fish
   fish/functions/h2b.fish
   fish/functions/h2d.fish
   fish/functions/h2h.fish
   fish/functions/h2o.fish
   fish/functions/o2b.fish
   fish/functions/o2d.fish
   fish/functions/o2h.fish
   fish/functions/o2o.fish
   git/config
   kanshi/config
   mako/config
   mpd/mpd.conf
   sway/config
   sway/config_bg_color
   sway/config_bg_picture
   systemd/user/kanshi.service
   systemd/user/mako.service
   systemd/user/sway-session.target
   waybar/config
   waybar/style.css
   wofi/config
   wofi/style.css
'

SSH_FILES='
   config
'

BLOOP_FILES='
   bloop.json
'

CABAL_FILES='
   config
'

RM_TARGET_ITEMS="
   $HOME/.gitconfig
   $HOME/.mako
   $HOME/.sway
   $HOME/.vimrc
   $XDG_CONFIG_HOME/nvim/lua/grs/core
   $XDG_CONFIG_HOME/nvim/lua/grs/utils
   $XDG_CONFIG_HOME/nvim/lua/grs/plugins/ide
"

DIRS_TO_CREATE="
   $HOME/catch
   $HOME/.local/bin
   $HOME/.cabal/bin
   $XDG_CONFIG_HOME/mpd/playlists
"

### Install git submodules
 (
    NVIM_GIT_REPO="${DOTFILE_GIT_REPO}/config/nvim"
    . ./config/nvim/nvInstall
 ) &

### Install or Check

## Install home directory files
for home_file in $HOME_FILES
do
   install_file "$HOME" "$home_file" ./home 0644 "$switch"
done

## Install  ~/bin  scripts
for bin_file in $BIN_SCRIPTS
do
   install_file "$HOME/bin" "$bin_file" ./home/bin 0755 "$switch"
done
chmod 0755 "$HOME/bin"

## Install configuration files

# Install Bloop Configs for Scala
for bloop_file in $BLOOP_FILES
do
   install_file "$HOME/.bloop" "$bloop_file" ./home/bloop 0600 "$switch"
done
chmod 0755 "$HOME/.bloop"

# Install Cabal Configs for Haskell
for cabal_file in $CABAL_FILES
do
   install_file "$HOME/.cabal" "$cabal_file" ./home/cabal 0644 "$switch"
done
chmod 0755 "$HOME/.cabal"

# Install $XDG_CONFIG_HOME files
for conf_file in $CONFIG_FILES
do
   install_file "$XDG_CONFIG_HOME" "$conf_file" ./config 0644 "$switch"
done
chmod 0755 "$HOME/.config"

# Install SSH Configs
for ssh_file in $SSH_FILES
do
   install_file "$HOME/.ssh" "$ssh_file" ./home/ssh 0600 "$switch"
done
chmod 0700 "$HOME/.ssh"

### Some final tweaks, checks & cleanup

# Create or report on missing directories
for DIR in $DIRS_TO_CREATE
do
   ensure_dir "$DIR"
done

# Remove/report no longer needed files and directories
for item in $RM_TARGET_ITEMS
do
   remove_item "$item" target
done

# Some final adjustments/tweaks/tasks
case "$switch" in
   install)
      ## Setup sway output configuration
      # The background picture I personally use is from
      # 'https://www.facebook.com/alittleofmeinyou/photos/325964185818238'
      picture="$HOME"/Pictures/Desktops/SwayBG.jpg
      bg_link="$XDG_CONFIG_HOME"/sway/config_bg
      if test -f "$picture"
      then
         bg="$XDG_CONFIG_HOME"/sway/config_bg_picture
      else
         bg="$XDG_CONFIG_HOME"/sway/config_bg_color
      fi
      test -L "$bg_link" && rm "$bg_link"
      ln -s "$bg" "$bg_link"

      ## Reload Systemd services in case config files get updated
      systemctl --user daemon-reload
      ;;
   repo)
      # Get git status info on repo
      printf '\nGit Status:\n'
      git status -s
      ;;
   target)
      :
      ;;
esac
