#!/bin/sh
#  Installs ani entire Linix desktop environment into $HOME directory
#  uses the following GitHub repos as submodules:
#
#    grscheller/home
#    grscheller/fish
#    grscheller/nvim
#    grscheller/sway-env
#
# shellcheck disable=SC3043
#   SC3043: allow use of non-POSIX keyword "local"
#
# Tested with both dash and bash.
#

export MyRepoName=dotfiles
export MyScriptName=dfInstall

XDG_CONFIG_HOME="${XDG_CONFIG_HOME:=$HOME/.config}"
DOTFILE_GIT_REPO="${DOTFILE_GIT_REPO:=$HOME/devel/dotfiles}"
umask 0022

cd "$DOTFILE_GIT_REPO" || {
   printf '\n%s: Error - failed to cd into "%s"\n' "$scriptName" "$DOTFILE_GIT_REPO"
   return 1
}

## Parse cmdline arguments and source functions
switch=''
. ./installSource.sh

## Installation configuration

df_Config_Files='
   git/config
'

df_Remove_Items="
   $HOME/.gitconfig
"

df_Dirs_To_Create=""

## Install/Check

ensure_dir "$XDG_CONFIG_HOME"
chmod 0755 "$XDG_CONFIG_HOME"

# Install git submodules boldly in parallel in subshells
# with a single instance of sh (tested with Dash and Bash).
 FISH_GIT_REPO="${DOTFILE_GIT_REPO}/config/fish"
 NVIM_GIT_REPO="${DOTFILE_GIT_REPO}/config/nvim"
 HOME_GIT_REPO="${DOTFILE_GIT_REPO}/home"
 SWAY_GIT_REPO="${DOTFILE_GIT_REPO}/sway-env"
 
 ( . ./config/fish/fishInstall ) &
 ( . ./config/nvim/nvInstall ) &
 ( . ./home/homeInstall ) &
 ( . ./sway-env/swayInstall ) &

# Install miscellaneous $XDG_CONFIG_HOME configuration files
install_files "$XDG_CONFIG_HOME" "$df_Config_Files" ./config 0644

# Remove/report no longer needed files and directories
remove_items "$df_Remove_Items"

# Create/report missing directories
ensure_dirs "$df_Dirs_To_Create"

# Adjustments/tweaks/tasks
case "$switch" in
   install)
      :
      ;;
   repo)
      git_status
      ;;
   target)
      :
      ;;
esac
