#!/usr/bin/fish
#
#  Toggle in a symlink ~/.config/nvim/lua -> .../dotfiles/config/nvim/lua
#
#  Sumneko_lua, at least when configured with the Neovim runtime
#  path, will put ~/.config/nvim files into its "workspace" in ways
#  which override the corresponding source repo source files.
#
#  This script is a "temporary" hack until I better understand
#  how to configure sumneko_lua not to do this.
#

set -q XDG_CONFIG_HOME; or set -lx XDG_CONFIG_HOME ~/.config
set -q DOTFILE_GIT_REPO; or set -gx DOTFILE_GIT_REPO ~/devel/dotfiles

if test -d ~/.config/nvim_lua_grs_backup
   rm $XDG_CONFIG_HOME/nvim/lua/grs
   mv $XDG_CONFIG_HOME/nvim_lua_grs_backup $XDG_CONFIG_HOME/nvim/lua/grs
   printf '\nEdit nvim config files directly in %s.' $DOTFILE_GIT_REPO
   printf '\nIssue git commands from dotfiles repo, %s.' $DOTFILE_GIT_REPO
   printf '\nThe dotfileInstall script will now work.\n'
   cd $DOTFILE_GIT_REPO
else
   mv ~/.config/nvim/lua/grs ~/.config/nvim_lua_grs_backup
   ln -s $DOTFILE_GIT_REPO/config/nvim/lua/grs $XDG_CONFIG_HOME/nvim/lua/grs
   printf '\nEdit nvim config files thru %s/nvim/lua/grs.' $XDG_CONFIG_HOME
   printf '\nStill issue git commands from %s.' $DOTFILE_GIT_REPO
   printf '\nThe dotfileInstall script will fail!!!\n'
   cd $XDG_CONFIG_HOME/nvim
end
