#!/bin/sh
#
# nvimInstall: Installs Neovim configuration files.
#
# shellcheck shell=dash
#

scriptName=ksInstall
envName=nvim-ks-env

gitRepo="${DOTFILES_GIT_REPO:=$HOME/devel/dotfiles}"
envPath="$gitRepo/$envName"

cd "$envPath" || {
   printf '%s: Error - Failed to cd into "%s"\n\n' "$scriptName" "$envPath"
   return 1
}

# Parse cmdline arguments and source functions, if not done already
. ../bin/.setup.sh

dot_config_files='
   ftplugin/c.lua
   ftplugin/cpp.lua
   ftplugin/csv.lua
   ftplugin/fish.lua
   ftplugin/haskell.lua
   ftplugin/help.lua
   ftplugin/html.lua
   ftplugin/lua.lua
   ftplugin/markdown.lua
   ftplugin/ocaml.lua
   ftplugin/rust.lua
   ftplugin/sbt.lua
   ftplugin/scala.lua
   ftplugin/sh.lua
   ftplugin/text.lua
   ftplugin/tsv.lua
   lua/grs/config/autocmds.lua
   lua/grs/config/keymaps.lua
   lua/grs/config/globals.lua
   lua/grs/config/options.lua
   lua/grs/lib/functional.lua
   lua/grs/lib/scroll.lua
   lua/grs/lib/text.lua
   lua/grs/plugins/autopairs.lua
   lua/grs/plugins/debug.lua
   lua/grs/plugins/gitsigns.lua
   lua/grs/plugins/indent_line.lua
   lua/grs/plugins/kickstart.lua
   lua/grs/plugins/linters_formatters/init.lua
   lua/grs/plugins/linters_formatters/formatters.lua
   lua/grs/plugins/linters_formatters/linters.lua
   lua/grs/plugins/lsp/init.lua
   lua/grs/plugins/lsp/cmp.lua
   lua/grs/plugins/lsp/lsp.lua
   lua/grs/plugins/neo-tree.lua
   spell/en.utf-8.add
   init.lua
'

toml_files='
   stylua.toml
'

remove_items="
   $XDG_CONFIG_HOME/nvim/lua/grs/plugins/formatters.lua
   $XDG_CONFIG_HOME/nvim/lua/grs/plugins/lint.lua
   $XDG_CONFIG_HOME/nvim/lua/grs/plugins/linters_formatters/lint.lua
"

dirs_to_create=""

## Preinstall checks

# See if nvim spellfile will need to be recompiled
SpellFile="$XDG_CONFIG_HOME/nvim/spell/en.utf-8.add"
if which nvim >/dev/null 2>&1
then
   if ! test -e "$SpellFile" || {
      ! diff -q "$SpellFile" config/nvim/spell/en.utf-8.add >/dev/null 2>&1
   }
   then
      compileSpellFile=yes
   fi
   if ! test -e "${SpellFile}.spl"
   then
      compileSpellFile=yes
   fi
else
   compileSpellFile=no
fi

## Install/Check

# Install Neovim files & NVIM related TOML files
process_files "$XDG_CONFIG_HOME/nvim" "
   $dot_config_files
   $toml_files
" config/nvim 0644 "$envPath"
chmod 0755 "$XDG_CONFIG_HOME/nvim"

# Remove/report no longer needed files and directories thru
remove_items "$remove_items"

# Create/report missing directories
ensure_dirs "$dirs_to_create"

## Post install/check tweaks

case "$OPTION_GIVEN" in
   install)
      # Helps when editing installed Neovim configs
      printf '{}' > "$XDG_CONFIG_HOME"/nvim/.neoconf.json

      # Recompiled spell file if necessary
      if test "$compileSpellFile" = yes
      then
         sf="${SpellFile##*/}" 
         sf_dir="${SpellFile%/*}"
         ( if cd "$sf_dir"
           then
              nvim -c ":mkspell! $sf" -c 'q' "$sf"
           fi )
      fi
      ;;
   check)
      # Indicate whether the spellfile will be recompiled on next install
      if test "$compileSpellFile" = yes
      then
         printf 'nvimInstall: Spellfile "%s" will be\n' "$SpellFile"
         printf '             recompiled on the next install.\n\n'
      fi
      ;;
   remove)
      remove_items "$XDG_CONFIG_HOME/nvim/lua/grs"
      :
      ;;
esac
