--[[ Install Language Modules for Neovim's built-in Treesitter ]]

return {

   {
      'nvim-treesitter/nvim-treesitter',
      opts = {
         ensure_installed = {
            'awk',
            'bash',
            'c',
            'clojure',
            'cmake',
            'comment',
            'cpp',
            'css',
            'diff',
            'fish',
            'fortran',
            'git_rebase',
            'gitattributes',
            'gitcommit',
            'gitignore',
            'go',
            'haskell',
            'help',
            'html',
            'java',
            'javascript',
            'json',
            'julia',
            'kotlin',
            'latex',
            'llvm',
            'lua',
            'make',
            'markdown',
            'markdown_inline',
            'norg',
            'python',
            'query',
            'r',
            'racket',
            'regex',
            'rust',
            'scala',
            'toml',
            'tsx',
            'typescript',
            'vim',
            'yaml',
            'zig',
         },
         sync_install = false,
         highlight = {
            enable = true,
            additional_vim_regex_highlighting = false,
         },
      },
   },
}
