--[[ Ensure Installation ]]

local M = {}

-- Treesitter parsers to ensure installed
M.treesitter_parsers = {
   'awk',
   'bash',
   'c',
   'clojure',
   'cmake',
   'cpp',
   'css',
   'diff',
   'fish',
   'fortran',
   'git_rebase',
   'gitattributes',
   'gitcommit',
   'gitignore',
   'go',
   'haskell',
   'html',
   'java',
   'javascript',
   'json',
   'jsonc',
   'julia',
   'kotlin',
   'latex',
   'llvm',
   'lua',
   'make',
   'markdown',
   'markdown_inline',
   'norg',
   'ocaml',
   'python',
   'query',
   'r',
   'racket',
   'regex',
   'rust',
   'scala',
   'toml',
   'tsx',
   'typescript',
   'vim',
   'vimdoc',
   'yaml',
   'zig',
}

M.linters = {
   ccs = { 'stylelint' },
   gitcommit ={ 'gitlint' },
   javascript = { 'eslint_d' },
   -- javascriptreact = { 'eslint' },
   json = { 'jsonlint' },
   lua = { 'selene' },
   luau = { 'selene' },
   markdown = { 'markdownlint' },
   sh = { 'shellcheck' },
   typescript = { 'eslint_d' },
   -- vue = { 'eslint_d' },
   -- svelte = { 'eslint_d' },
}

return M
