#!/bin/sh
#
# swayInstall: Installs Sway WM configuration files.
#
#   Systemd user Services used:
#     kanshi - Wayland daemon that automatically configures outputs
#     mako - Notification daemon for Wayland
#     mpd - Music daemon for Linux
#

scriptName=swayInstall
envName=sway-env

gitRepo="${DOTFILES_GIT_REPO:=$HOME/devel/dotfiles}"
envPath="$gitRepo/$envName"

cd "$envPath" || {
   printf '%s: Error - failed to cd into "%s"\n\n' "$scriptName" "$envPath"
   return 1
}

XDG_STATE_HOME="${XDG_STATE_HOME:=$HOME/.local/state}"
XDG_CACHE_HOME="${XDG_CACHE_HOME:=$HOME/.cache}"

## Files to install

dot_config_files='
   alacritty/alacritty_arch.toml
   alacritty/alacritty.toml
   alacritty/alacritty_arch.yml
   alacritty/alacritty.yml
   kanshi/config
   mako/config
   mpd/mpd.conf
   sway/config
   sway/config_bg_color
   sway/config_bg_picture
   waybar/config
   waybar/style.css
   wofi/config
   wofi/style.css
'

systemd_service_files='
   kanshi.service
   mako.service
   sway-session.target
'

bin_scripts='
   startw
'

remove_items="
   $HOME/.mako
   $HOME/.mpd
   $HOME/.sway
"

dirs_to_create="
   $XDG_CONFIG_HOME/mpd/playlists
   $XDG_STATE_HOME/mpd/
   $XDG_CACHE_HOME/mpd/
"

## Setup - parse cmdline arguments and source functions, if not done already

. ../bin/.setup.sh

## Install or Check

# Install Sway config files
install_files "$XDG_CONFIG_HOME" "$dot_config_files" config 0644 "$envPath"

# Install Sway related Systemd service files
install_files "$XDG_CONFIG_HOME/systemd/user" "$systemd_service_files" config/systemd/user 0644 "$envPath"

# Install ~/bin scripts
install_files "$HOME/bin" "$bin_scripts" bin 0755 "$envPath"
chmod 0755 "$HOME/bin"

# Remove/report no longer needed files and directories
remove_items "$remove_items"

# Create/report missing directories
ensure_dirs "$dirs_to_create"

# Adjustments/tweaks/tasks
case "$dfOption" in
   install)
      # The background picture I personally use is from
      # 'https://www.facebook.com/alittleofmeinyou/photos/325964185818238'
      picture="$HOME"/Pictures/Desktops/SwayBG.jpg
      bg_link="$XDG_CONFIG_HOME"/sway/config_bg
      if test -f "$picture"
      then
         bg="$XDG_CONFIG_HOME"/sway/config_bg_picture
      else
         bg="$XDG_CONFIG_HOME"/sway/config_bg_color
      fi
      test -L "$bg_link" && rm "$bg_link"
      ln -s "$bg" "$bg_link"

      # Reload Systemd user services in case config files get updated
      systemctl --user daemon-reload
      :
      ;;
   check)
      :
      ;;
esac
