#!/bin/sh
#
# shellcheck shell=dash
#

scriptName=bashInstall
envName=bash-env

gitRepo="${DOTFILES_GIT_REPO:=$HOME/devel/dotfiles}"
envPath="$gitRepo/$envName"

cd "$envPath" || {
   printf 'Error %s: failed to cd into "%s"\n\n' "$scriptName" "$envPath"
   return 1
}

bash_files='
   .bash_profile
   .bashrc
   .inputrc
'

## Setup - parse cmdline arguments and source functions, if not done already

. ../bin/.setup.sh

## Preinstall checks

## Install, Check or Remove

# Process bash config files
process_files "$HOME" "$bash_files" . 0644 "$envPath"

case "$dfOption" in
   install)
      :
      ;;
   check)
      :
      ;;
   remove)
      :
      ;;
esac
