#!/bin/sh
#
#  Installs my Neovim environment into my $HOME directory.
#

scriptName=nvimInstall
envName=nvim-env

gitRepo="${DOTFILE_GIT_REPO:=$HOME/devel/dotfiles}"
envPath="$gitRepo/$envName"

cd "$envPath" || {
   printf '%s: Error - Failed to cd into "%s"\n\n' "$scriptName" "$envPath"
   return 1
}

## Parse cmdline arguments and source functions, if not done already
. "$gitRepo/bin/.setup.sh"

nv_config_files='
   ftplugin/c.lua
   ftplugin/cpp.lua
   ftplugin/csv.lua
   ftplugin/fish.lua
   ftplugin/haskell.lua
   ftplugin/help.lua
   ftplugin/html.lua
   ftplugin/lua.lua
   ftplugin/markdown.lua
   ftplugin/ocaml.lua
   ftplugin/rust.lua
   ftplugin/sbt.lua
   ftplugin/scala.lua
   ftplugin/sh.lua
   ftplugin/text.lua
   ftplugin/tsv.lua
   lua/grs/config/autocmds.lua
   lua/grs/config/globals.lua
   lua/grs/config/keymaps.lua
   lua/grs/config/options.lua
   lua/grs/config/treesitter.lua
   lua/grs/lib/functional.lua
   lua/grs/lib/scroll.lua
   lua/grs/lib/text.lua
   lua/grs/plugins/coding/init.lua
   lua/grs/plugins/coding/harpoon.lua
   lua/grs/plugins/coding/refactoring.lua
   lua/grs/plugins/editor/init.lua
   lua/grs/plugins/editor/colorscheme.lua
   lua/grs/plugins/editor/noice.lua
   lua/grs/plugins/editor/telescope.lua
   lua/grs/plugins/editor/textedit.lua
   lua/grs/plugins/editor/whichkey.lua
   lua/grs/plugins/linters_formatters/init.lua
   lua/grs/plugins/linters_formatters/formatters.lua
   lua/grs/plugins/linters_formatters/linters.lua
   lua/grs/plugins/lsp/init.lua
   lua/grs/plugins/lsp/cmp.lua
   lua/grs/plugins/lsp/lsp.lua
   lua/grs/plugins/lsp/rust.lua
   lua/grs/plugins/lsp/scala.lua
   lua/grs/plugins/common.lua
   spell/en.utf-8.add
   init.lua
'

nv_toml_files='
   selene.toml
   stylua.toml
   vim.toml
'

nv_remove_items=""

nv_dirs_to_create=""

## Install/Check

# Install Neovim files & NVIM related TOML files
install_files "$XDG_CONFIG_HOME/nvim" "
   $nv_config_files
   $nv_toml_files
" config/nvim 0644 "$envPath"
chmod 0755 "$XDG_CONFIG_HOME/nvim"

# Remove/report no longer needed files and directories thru
remove_items "$nv_remove_items"

# Create/report missing directories
ensure_dirs "$nv_dirs_to_create"

# Adjustments/tweaks/tasks
case "$switch" in
   install)
      printf '{}' > "$XDG_CONFIG_HOME"/nvim/.neoconf.json
      ;;
   check)
      SpellFile="$XDG_CONFIG_HOME/nvim/spell/en.utf-8.add"
      if ! test -e "$SpellFile" || ! diff -q "$SpellFile" config/nvim/spell/en.utf-8.add 2>/dev/null
      then
         printf '\nThe spell file %s will need to be compiled after the install:\n\n' "$SpellFile"
         printf "  $ cd %s; nvim -c ':mkspell! %%' -c 'q' %s; cd -\n\n" "${SpellFile%/*}/" "${SpellFile##*/}"
      fi
      ;;
esac
