#!/bin/sh
#
# homeInstall: Installs a basic Bash environment and other
#              miscellaneous home directory configuration files,
#
#   - bash (startup files)
#   - ~/bin scripts
#   - ssh
#   - bloop (Scala), Cabal (Haskell)
#   - create directories important to my work flow
#

scriptName=homeInstall
envName=home-env

gitRepo="${DOTFILES_GIT_REPO:=$HOME/devel/dotfiles}"
envPath="$gitRepo/$envName"

cd "$envPath" || {
   printf 'Error %s: failed to cd into "%s"\n\n' "$scriptName" "$envPath"
   return 1
}

bin_scripts='
   buArch
   chkcolor
   codepoint
   digpath
   etherApe
   monitor
   myCalc
   pathtrim
   rt
   spin
   viewJarManifest
'

ssh_files='
   config
'

bloop_files='
   bloop.json
'

cabal_files='
   config
'

dot_config_files='
   git/config
   nixpkgs/config.nix
'

devel_files='
   python_venvs/ve.conf
'

remove_items="
   $HOME/.vimrc
"

dirs_to_create="
   $HOME/catch
   $HOME/.cabal/bin
   $HOME/.local/bin
"

## Setup - parse cmdline arguments and source functions, if not done already

. ../bin/.setup.sh

## Install, Check or Remove

# Process ~/bin scripts
process_files "$HOME/bin" "$bin_scripts" bin 0755 "$envPath"
chmod 0755 "$HOME/bin"

# Process ssh configs
process_files "$HOME/.ssh" "$ssh_files" ssh 0600 "$envPath"
chmod 0700 "$HOME/.ssh"

# Process Bloop configs for Scala
process_files "$HOME/.bloop" "$bloop_files" bloop 0644 "$envPath"
chmod 0755 "$HOME/.bloop"

# Process Cabal configs for Haskell
process_files "$HOME/.cabal" "$cabal_files" cabal 0644 "$envPath"
chmod 0755 "$HOME/.cabal"

# Process miscellaneous ~/.config files
process_files "$XDG_CONFIG_HOME" "$dot_config_files" config 0644 "$envPath"

# Process devel config files
process_files "$HOME/devel" "$devel_files" devel 0644 "$envPath"
chmod 0755 "$HOME/devel"

# Remove/report no longer needed files and directories
remove_items "$remove_items"

# Create/report missing directories
ensure_dirs "$dirs_to_create"

## Post install/check tweaks

case "$dfOption" in
   install)
      :
      ;;
   check)
      :
      ;;
   remove)
      remove_item "$XDG_CONFIG_HOME"/nixpkgs
      ;;
esac
