#!/bin/sh
#
# homeInstall: Installs a basic Bash environment and other
#              miscellaneous home directory configuration files,
#
#   - bash (startup files)
#   - ~/bin scripts
#   - ssh
#   - bloop (Scala), Cabal (Haskell)
#   - create directories important to my work flow
#

scriptName=homeInstall
envName=home-env

gitRepo="${DOTFILES_GIT_REPO:=$HOME/devel/dotfiles}"
envPath="$gitRepo/$envName"

cd "$envPath" || {
   printf 'Error %s: failed to cd into "%s"\n\n' "$scriptName" "$envPath"
   return 1
}

bash_files='
   .bash_profile
   .bashrc
   .inputrc
'

bin_scripts='
   buArch
   chkcolor
   codepoint
   digpath
   etherApe
   monitor
   myCalc
   pathtrim
   rt
   spin
   viewJarManifest
'

bloop_files='
   bloop.json
'

cabal_files='
   config
'

dot_config_files='
   git/config
   nixpkgs/config.nix
'
remove_items="
   $HOME/.vimrc
"

ssh_files='
   config
'

dirs_to_create="
   $HOME/catch
   $HOME/.cabal/bin
   $HOME/.local/bin
"

## Setup - parse cmdline arguments and source functions, if not done already

. ../bin/.setup.sh

## Preinstall checks

## Install or Check

# Install bash config files
install_files "$HOME" "$bash_files" . 0644 "$envPath"

# Install ~/bin scripts
install_files "$HOME/bin" "$bin_scripts" bin 0755 "$envPath"
chmod 0755 "$HOME/bin"

# Install ssh configs
install_files "$HOME/.ssh" "$ssh_files" ssh 0600 "$envPath"
chmod 0700 "$HOME/.ssh"

# Install Bloop configs for Scala
install_files "$HOME/.bloop" "$bloop_files" bloop 0644 "$envPath"
chmod 0755 "$HOME/.bloop"

# Install Cabal configs for Haskell
install_files "$HOME/.cabal" "$cabal_files" cabal 0644 "$envPath"
chmod 0755 "$HOME/.cabal"

# Install miscellaneous ~/.config files
install_files "$HOME/.config" "$dot_config_files" config 0644 "$envPath"
chmod 0755 "$HOME/.cabal"

# Remove/report no longer needed files and directories
remove_items "$remove_items"

# Create/report missing directories
ensure_dirs "$dirs_to_create"

## Post install/check tweaks

case "$dfOption" in
   install)
      :
      ;;
   check)
      :
      ;;
esac
