#!/bin/sh
#
#  Installs a basic Bash environment and other home
#  directory miscellaneous configurations and tweaks.
#
#  - bash (startup files)
#  - ~/bin scripts
#  - ssh
#  - bloop (Scala), Cabal (Haskell)
#  - create directories important to my work flow
#  - remove items
#

scriptName=homeInstall
envName=home-env

gitRepo="${DOTFILE_GIT_REPO:=$HOME/devel/dotfiles}"
envPath="$gitRepo/$envName"

cd "$envPath" || {
   printf 'Error %s: failed to cd into "%s"\n\n' "$scriptName" "$envPath"
   return 1
}

## Parse cmdline arguments and source functions, if not done already
. "$gitRepo/bin/.setup.sh"

home_files='
   .bash_profile
   .bashrc
   .inputrc
'

home_bin_scripts='
   buArch
   chkcolor
   codepoint
   digpath
   etherApe
   monitor
   myCalc
   pathtrim
   rt
   spin
   viewJarManifest
'

home_bloop_files='
   bloop.json
'

home_cabal_files='
   config
'

home_config_files='
   git/config
   nixpkgs/config.nix
'
home_remove_items="
   $HOME/.vimrc
"

home_ssh_files='
   config
'

home_ensure_dirs_exist="
   $HOME/catch
   $HOME/.local/bin
   $HOME/.cabal/bin
"

## Install or Check

# Install bash config files
install_files "$HOME" "$home_files" . 0644 "$envPath"

# Install ~/bin scripts
install_files "$HOME/bin" "$home_bin_scripts" bin 0755 "$envPath"
chmod 0755 "$HOME/bin"

# Install ssh configs
install_files "$HOME/.ssh" "$home_ssh_files" ssh 0600 "$envPath"
chmod 0700 "$HOME/.ssh"

# Install Bloop configs for Scala
install_files "$HOME/.bloop" "$home_bloop_files" bloop 0644 "$envPath"
chmod 0755 "$HOME/.bloop"

# Install Cabal configs for Haskell
install_files "$HOME/.cabal" "$home_cabal_files" cabal 0644 "$envPath"
chmod 0755 "$HOME/.cabal"

# Install miscellaneous ~/.config files
install_files "$HOME/.config" "$home_config_files" config 0644 "$envPath"
chmod 0755 "$HOME/.cabal"

# Remove/report no longer needed files and directories
remove_items "$home_remove_items"

# Create/report missing directories
ensure_dirs "$home_ensure_dirs_exist"

## Adjustments/tweaks/tasks
case "$switch" in
   install)
      :
      ;;
   check)
      :
      ;;
esac
